### ISSUE TITLE
无法支持网页端的Hi-Res音频投稿选项

### ISSUE THREAD

**Issue by LidoCKT** [ForgQi/biliup-app#59]
![image](https://user-images.githubusercontent.com/24887103/209303577-f6af8ecd-568a-4d48-b0e9-ad52535d8704.png)

这个标准其实不高 BD自带的PCM音轨就能满足条件
Biliup-app无法支持这个选项

这个选项只有在首次投稿的时候勾上才行 最初的视频不支持这个标准或者投稿时没有勾选则无法再次编辑勾选

![image](https://user-images.githubusercontent.com/24887103/209304018-05bd087b-fdee-4e0e-9580-42a605820c50.png)
如果网页端先传一个符合条件的视频 然后使用biliip-app换源 发现投稿还是没有Hi-Res音频
即便进入编辑界面发现这个勾还是勾上的

**Comment by JokerQyou** [comment]
This requires an upstream commit ([Hi-Res Support](https://github.com/ForgQi/biliup-rs/pull/46/commits/d291c76bd8aff02f3ca78cb26cc1bbe73e7c7ea2)) that is not yet available on crates.io. @ForgQi Is it feasible to release a new version of `biliup-rs` to crates.io?

**Comment by JokerQyou** [comment]
Upon further investigation, the problem lies deeper inside the `biliup` library - it uses the mobile client APIs, and they do not support some new parameters. For example `http://member.bilibili.com/x/client/archive/view?access_key={}&{vid}` does not return `lossless_music` field, you need to use `https://member.bilibili.com/x/vupre/web/archive/view?{vid}` (the API used by the web UI).

Unfortunately I have not yet successfully compiled `biliup` crate locally. It seems like the master branch contains error regarding SQL modules which I'm not familiar with.

**Comment by ForgQi** [comment]
@JokerQyou 感谢你的调查，如果需要帮助可以加QQ群130816738进行更深入的交流

**Comment by JokerQyou** [comment]
@ForgQi 呃，我可能不太方便加群，电脑上没有 QQ。我看了下 `billiup-rs` 的 master 分支最新的 CI 检查也没有过，我本地编译遇到的问题跟 CI 日志里显示的是一样的。

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1465267/222877363-6233142b-a80b-443f-91ca-0fa293512c39.png">

先提了一个 PR，你可以看看代码，有问题我再调整。如果不切换（或者添加）web 界面的 API 的话应该只能做到这种程度了。
